#
# ~~~ Common
spring.application.name=c3-dojo
spring.threads.virtual.enabled=true
server.servlet.context-path=/api
#
# ~~~ Database & Migration
spring.liquibase.database-change-log-lock-table=db_change_locks
spring.liquibase.database-change-log-table=db_change_logs
spring.liquibase.change-log=classpath:db/changelog/master.xml
#
# ~~~ Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.generate_statistics=true
#
# ~~~ Katas
# ? spring_feature_flags
my.custom.features.regex-sanitizer-enabled=false
# ? spring_ai_rag
spring.ai.ollama.embedding.model=llama3.1
spring.ai.ollama.chat.options.model=llama3.1
spring.ai.ollama.init.pull-model-strategy=always
