#
# ~~~ Common
spring.application.name=c3-dojo
spring.threads.virtual.enabled=true
server.servlet.context-path=/api
#
# ~~~ Transactions, Database & Schema Migration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.open-in-view=false
spring.liquibase.database-change-log-lock-table=db_change_locks
spring.liquibase.database-change-log-table=db_change_logs
spring.liquibase.change-log=classpath:db/changelog/master.xml
#
# ~~~ Observability
management.server.port=8081
management.endpoints.web.base-path=/actuator
management.metrics.enable.all=true
management.endpoints.web.exposure.include=*
c3.dojo.management.username=actuator
c3.dojo.management.password=change_me!
spring.ai.chat.observations.log-prompt=true
spring.ai.chat.observations.log-completion=true
spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.client.observations.log-completion=true
#
# ~~~ Katas
# -> spring_feature_flags
my.custom.features.regex-sanitizer-enabled=false
# -> spring_ai_rag
spring.ai.ollama.init.pull-model-strategy=always
spring.ai.ollama.chat.model=llama3.1
spring.ai.ollama.chat.options.model=llama3.1
spring.ai.ollama.embedding.model=llama3.1
# -> spring_ai_mcp
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.stdio.servers-configuration=classpath:/spring_ai_mcp/mcp-servers-config.json
logging.level.io.modelcontextprotocol.client=info
logging.level.io.modelcontextprotocol.spec=info
